# General configuration
approval_policy = "on-failure"
sandbox_mode = "workspace-write"

web_search_request = true
model = "gpt-5.1-codex-max"

[sandbox_workspace_write]
# Allow the command being run inside the sandbox to make outbound network
# requests. Disabled by default.
network_access = true

[mcp_servers."nixos"]
command = "uvx"
args = ["mcp-nixos"]

[mcp_servers."playwright"]
command = "npx"
args = ["@playwright/mcp", "--headless", "--browser=chromium"]

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
